version: '3.8'

services:
  book_store_postg:
      image: postgres:17.1
      container_name: book_store_postg
      env_file:
      - .env
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_DB=${DB_NAME}
        - POSTGRES_USER=${DB_USERNAME}
        - POSTGRES_PASSWORD=${DB_PASSWORD}

  book_stor_api:
    build:
      context: .
    container_name: my-fast-api-containe
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
    ports:
      - "80:80"
    depends_on:
      - book_store_postg
    env_file:
      - .env
    command: ['sh', 'bin/boot.sh']
